[versions]
# Kotlin
kotlin-version = "2.0.21" # https://github.com/JetBrains/kotlin
kotlin-coroutines = "1.9.0" # https://github.com/Kotlin/kotlinx.coroutines
kotlin-android-application = "8.7.2" # https://developer.android.com/build/releases/gradle-plugin
kotlin-serialization-json = "1.7.3" # https://github.com/Kotlin/kotlinx.serialization

# Androidx
androidx-material = "1.12.0" # https://github.com/material-components/material-components-android
androidx-compose-bom = "2024.10.01" # https://developer.android.com/jetpack/androidx/releases/compose#versions
androidx-room = "2.6.1" # https://developer.android.com/jetpack/androidx/releases/room
androidx-activity-compose = "1.9.3" # https://developer.android.com/jetpack/androidx/releases/activity
leakcanary = "2.14" # https://github.com/square/leakcanary
androidx-splash = "1.0.1" # https://developer.android.com/jetpack/androidx/releases/core

# Google
google-coroutinesPlayServices = "1.9.0" # https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-play-services
google-auth = "21.2.0" # https://developers.google.com/android/guides/setup
google-crashlytics = "3.0.2" # https://firebase.google.com/docs/crashlytics/get-started
google-services = "4.4.2" # https://developers.google.com/android/guides/google-services-plugin
google-accompanist = "0.36.0" # https://github.com/google/accompanist
google-firebase-bom = "33.5.1" # https://firebase.google.com/support/release-notes/android

# Testw
tests-assertk = "0.28.1" # https://github.com/willowtreeapps/assertk
tests-turbine = "1.2.0" # https://github.com/cashapp/turbine

# Other
ktor = "3.0.1" # https://github.com/ktorio/ktor

# klibs
klibs-mikro = "1.8.8" # https://github.com/makeevrserg/klibs.mikro
klibs-kstorage = "3.2.0" # https://github.com/makeevrserg/klibs.kstorage
klibs-kdi = "1.4.8" # https://github.com/makeevrserg/KDI

# Compose
kotlin-compose = "1.7.0+" # https://github.com/JetBrains/compose-multiplatform

# Moko
moko-mvvm = "0.16.1" # https://github.com/icerockdev/moko-mvvm
moko-resources = "0.24.0" # https://github.com/icerockdev/moko-resources
moko-network = "0.21.0" # https://github.com/icerockdev/moko-network

# Decompose
decompose = "3.2.2" # https://github.com/arkivanov/Decompose
essenty = "2.2.1" # https://github.com/arkivanov/Essenty

# MVIKotlin
mvikotlin = "4.2.0" # https://github.com/arkivanov/MVIKotlin

# Settings
mppsettings = "1.2.0" # https://github.com/russhwolf/multiplatform-settings

# klibs
klibs-gradleplugin = "1.4.0" # https://github.com/makeevrserg/gradle-plugin

# buildkonfig
buildkonfig = "5.5.0" # https://github.com/gmazzo/gradle-buildconfig-plugin

[libraries]
# klibs
klibs-mikro-core = { module = "ru.astrainteractive.klibs:mikro-core", version.ref = "klibs-mikro" }
klibs-mikro-platform = { module = "ru.astrainteractive.klibs:mikro-platform", version.ref = "klibs-mikro" }
klibs-mikro-extensions = { module = "ru.astrainteractive.klibs:mikro-extensions", version.ref = "klibs-mikro" }
klibs-kstorage = { module = "ru.astrainteractive.klibs:kstorage", version.ref = "klibs-kstorage" }
klibs-kdi = { module = "ru.astrainteractive.klibs:kdi", version.ref = "klibs-kdi" }

# Settings
mppsettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "mppsettings" }

# MVIKotlin
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }

# Decompose
decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose" }
essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "google-coroutinesPlayServices" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

# Androidx
android-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splash" }

# Google
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "google-firebase-bom" }
google-firebase-crsahlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-crsahlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "google-crashlytics" }
google-gms-services-gradle = { module = "com.google.gms:google-services", version.ref = "google-services" }
google-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "google-auth" }
google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }

# Tests
tests-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "tests-assertk" }
tests-turbine = { module = "app.cash.turbine:turbine", version.ref = "tests-turbine" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-contentNegitiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Moko`
moko-network-generator = { module = "dev.icerock.moko:network-generator", version.ref = "moko-network" }
moko-mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko-mvvm" }
moko-mvvm-flow = { module = "dev.icerock.moko:mvvm-flow", version.ref = "moko-mvvm" }
moko-resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resources" }
moko-resources-core = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }

[plugins]
# Kotlin
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-version" }
kotlin-compose = { id = "org.jetbrains.compose", version.ref = "kotlin-compose" }
kotlin-compose-gradle = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }

# Android
android-library = { id = "com.android.application", version.ref = "kotlin-android-application" }
android-application = { id = "com.android.library", version.ref = "kotlin-android-application" }

# Gradle
gradle-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildkonfig" }

# klibs - core
klibs-gradle-detekt = { id = "ru.astrainteractive.gradleplugin.detekt", version.ref = "klibs-gradleplugin" }
klibs-gradle-detekt-compose = { id = "ru.astrainteractive.gradleplugin.detekt.compose", version.ref = "klibs-gradleplugin" }
klibs-gradle-dokka-root = { id = "ru.astrainteractive.gradleplugin.dokka.root", version.ref = "klibs-gradleplugin" }
klibs-gradle-dokka-module = { id = "ru.astrainteractive.gradleplugin.dokka.module", version.ref = "klibs-gradleplugin" }
klibs-gradle-java-core = { id = "ru.astrainteractive.gradleplugin.java.core", version.ref = "klibs-gradleplugin" }
klibs-gradle-stub-javadoc = { id = "ru.astrainteractive.gradleplugin.stub.javadoc", version.ref = "klibs-gradleplugin" }
klibs-gradle-publication = { id = "ru.astrainteractive.gradleplugin.publication", version.ref = "klibs-gradleplugin" }
klibs-gradle-rootinfo = { id = "ru.astrainteractive.gradleplugin.root.info", version.ref = "klibs-gradleplugin" }
# klibs - android
klibs-gradle-android-core = { id = "ru.astrainteractive.gradleplugin.android.core", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-compose = { id = "ru.astrainteractive.gradleplugin.android.compose", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-apk-sign = { id = "ru.astrainteractive.gradleplugin.android.apk.sign", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-apk-name = { id = "ru.astrainteractive.gradleplugin.android.apk.name", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-publication = { id = "ru.astrainteractive.gradleplugin.android.publication", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-namespace = { id = "ru.astrainteractive.gradleplugin.android.namespace", version.ref = "klibs-gradleplugin" }